import {
	loadTimeData
} from './load_time_data.m.js';
loadTimeData.data = {
	"bestScore": "最佳 $1 $2 $3",
	"bestScoreFlyout": "最佳成績: $1",
	"bestScoreMenuDisplay": "$1 $2",
	"cancel": "取消",
	"close": "關閉",
	"code": "作弊代碼激!",
	"codeCheat": "作弊代碼激! $1",
	"codeScoring": "改回合成績.",
	"congrats": "你戰勝了 $1% 的全球玩家!",
	"endlessBestScore": -1,
	"endlessDescriptor": "距離",
	"endlessModeTitleInline": "無盡:",
	"endlessTitle": "無盡",
	"endlessUnit": "m",
	"fontfamily": "system-ui, sans-serif",
	"fontsize": "75%",
	"gameCreditsButton": "遊戲製作群",
	"gameCreditsDialogTitle": "遊戲製作群",
	"gameMode": "遊戲模式已更變為 $1",
	"gameModeSelectLabel": "遊戲模式",
	"gameModeSelectLabelDisabled": "遊戲模式 (重新遊戲才可更改)",
	"gameSettings": "遊戲設定",
	"highVisibilityActive": false,
	"highVisiblityModeToggleLabel": "高可見度",
	"howToPlayButton": "遊玩方式",
	"howToPlayControllerBoost": "按 RT 來使用速度提高",
	"howToPlayControllerMovement": "使用搖桿或方向鍵來行進",
	"howToPlayControllerRefresh": "按下 LB+RB 以重新啟動遊戲",
	"howToPlayDialogTitle": "遊玩方式",
	"howToPlayEndless": "盡快前進並拯救朋友以協助您抵禦敵人",
	"howToPlayKeyboardBoost": "按 `F` 來使用速度提高",
	"howToPlayKeyboardMovement": "使用箭號或 `WASD` 鍵來移動",
	"howToPlayKeyboardRefresh": "重新整理頁面以重新啟動遊戲",
	"howToPlayMouseBoost": "按一下滑鼠右鍵來使用速度提高",
	"howToPlayMouseMovement": "移動滑鼠以行進",
	"howToPlayMouseRefresh": "重新整理頁面以重新啟動遊戲",
	"howToPlayTimeTrial": "盡快地到達終點並收集硬幣，以減少時間",
	"howToPlayTouchBoost": "向下撥動兩次以使用速度提高",
	"howToPlayTouchMovement": "撥動或點選以行進",
	"howToPlayTouchRefresh": "重新整理頁面以重新啟動遊戲",
	"howToPlayZigZag": "盡可能地連續衝過多個閘道",
	"isDebugMode": false,
	"isLinuxTuxEnabled": true,
	"isNewShare": false,
	"is_windows_xbox_sku": "false",
	"keyboardAction": "空格鍵",
	"language": "en",
	"lastSelectedMode": "endless",
	"lastSelectedPlayer": 1,
	"lastSelectedTheme": "surf",
	"menuInfo": "要開始遊戲",
	"mouseAction": "按兩下",
	"newBestScore": "新成績 $1 $2 $3",
	"newGame": "開始新遊戲",
	"off": "Off",
	"on": "On",
	"overInfo": "再玩一次遊戲",
	"overTitle": "好的嘗試!",
	"pauseInfo": "若要繼續玩遊戲",
	"pauseTitle": "遊戲暫停",
	"reducedSpeedActive": false,
	"reducedSpeedModeToggleLabel": "降低速度",
	"resetAllStats": "重設所有統計資料",
	"resetAllStatsDialogText": "確定要重設所有遊戲統計資料，包括最高記錄嗎??",
	"resetAllStatsDialogTitle": "重設所有統計資料",
	"share": "和朋友一起分享",
	"shareButtonString": "分享",
	"shareCopy": "複製",
	"shareLinkCopied": "已複製!",
	"shareLinkFlyout": "https://go.microsoft.com/fwlink/?linkid=2162539",
	"shareLinkGameOver": "https://go.microsoft.com/fwlink/?linkid=2168605",
	"shareNewLinkMobile": "https://microsoftedgewelcome.microsoft.com/emmx/edge-surf",
	"shareString": "我發現了一個超級有趣的遊戲，讓我們一起衝浪！",
	"skiTheme": "來滑雪吧",
	"specialThanks": "特別感謝:",
	"startShare": "開始分享",
	"surfTheme": "來衝浪吧",
	"textdirection": "ltr",
	"theme": "主題更變為 $1",
	"themeSelectLabel": "主題",
	"timetrialBestScore": -1,
	"timetrialDescriptor": "時間",
	"timetrialModeTitleInline": "計時賽:",
	"timetrialTitle": "計時賽",
	"timetrialUnit": "s",
	"touchAction": "兩下點擊",
	"zigzagBestScore": -1,
	"zigzagDescriptor": "streak",
	"zigzagModeTitleInline": "髮夾彎:",
	"zigzagTitle": "髮夾彎",
	"zigzagUnit": "匝道數"
};